name: CPython GMIC MacOS build
# Imitating https://github.com/vinecopulib/pyvinecopulib/blob/master/.github/workflows/pypi.yml

on: [push]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.5]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: build on macos
        working-directory: ./cpython
        env:
          PYTHON3: python3
          PIP3: pip3
          CIBW_BUILD: cp3*-*macosx*
          CIBW_BEFORE_BUILD: pip install -r dev-requirements.txt
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: python -W default -m pytest "{project_dir}/tests/test_gmic_install_and_run.py"
          MACOSX_DEPLOYMENT_TARGET: 10.10
        run: |
          brew install pkg-config fftw libpng
          #bash 00_all_steps.sh 
          bash 1_clean_and_regrab_gmic_src.sh
          # Install Github actions branch at https://github.com/mayeut/cibuildwheel/tree/github-workflows
          MACOSX_DEPLOYMENT_TARGET=10.10 pip install git+https://github.com/mayeut/cibuildwheel.git@github-workflows
          MACOSX_DEPLOYMENT_TARGET=10.10 python -m cibuildwheel --output-dir wheelhouse
          echo "Mac OS wheelhoose after cibuildwheel looks like:"
          bash 11_send_to_pypi.sh
